package tc;
import java.util.*;
/**
 *
 * @author jay
 */
public class TrainControllerGui extends javax.swing.JDialog {
    private int selectedTrainIndex = 0;
    private ArrayList<Train> trains;
    
    public TrainControllerGui(java.awt.Frame parent, boolean modal, ArrayList<Train> trains) {
        super(parent, modal);
        initComponents();
        
        this.trains = trains;
        Timer timer = new Timer();
        timer.schedule(new Progress(), 0,1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jSplitPane1 = new javax.swing.JSplitPane();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        TrainSelector = new javax.swing.JComboBox<>();
        CurrentSpeedLabel = new javax.swing.JLabel();
        SuggestedSpeedLabel = new javax.swing.JLabel();
        AuthorityLabel = new javax.swing.JLabel();
        CurrentStationHeader = new javax.swing.JLabel();
        ACLabel = new javax.swing.JLabel();
        LeftDoorsLabel = new javax.swing.JLabel();
        RightDoorsLabel = new javax.swing.JLabel();
        InteriorLightsLabel = new javax.swing.JLabel();
        HeadlightsLabel = new javax.swing.JLabel();
        KiLabel = new javax.swing.JLabel();
        KpLabel = new javax.swing.JLabel();
        ServiceBrakeLabel = new javax.swing.JLabel();
        ServiceBreakSlider = new javax.swing.JSlider();
        PowerLabel = new javax.swing.JLabel();
        PropertiesHeader = new javax.swing.JLabel();
        CommandsHeader = new javax.swing.JLabel();
        EmergencyBrake = new javax.swing.JToggleButton();
        ACValue = new javax.swing.JSpinner();
        RightDoorsValue = new javax.swing.JComboBox<>();
        LeftDoorsValue = new javax.swing.JComboBox<>();
        InteriorLightsValue = new javax.swing.JComboBox<>();
        HeadlightsValue = new javax.swing.JComboBox<>();
        FailureModesHeader = new javax.swing.JLabel();
        AnnouncementsLabel = new javax.swing.JLabel();
        AnnouncementsBox = new javax.swing.JScrollPane();
        AnnouncementsTextArea = new javax.swing.JTextArea();
        CurrentTrainHeader = new javax.swing.JLabel();
        CurrentStationValue = new java.awt.Label();
        PowerValue = new java.awt.Label();
        EngineFailureLabel = new java.awt.Label();
        SignalFailureLabel = new java.awt.Label();
        BrakeFailureLabel = new java.awt.Label();

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TrainSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "train 1", "train 2", "train 3", "train 4" }));
        TrainSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainSelectorActionPerformed(evt);
            }
        });

        CurrentSpeedLabel.setText("Current Speed:  0 mph");

        SuggestedSpeedLabel.setText("Suggested Speed:  0  mph");

        AuthorityLabel.setText("Authority:  0 ft.");

        CurrentStationHeader.setText("Current Station:");

        ACLabel.setText("A/C:");

        LeftDoorsLabel.setText("Left Doors:");

        RightDoorsLabel.setText("Right Doors:");

        InteriorLightsLabel.setText("Interior Lights:");

        HeadlightsLabel.setText("Headlights:");

        KiLabel.setText("Ki:    0");

        KpLabel.setText("Kp:  1.0");

        ServiceBrakeLabel.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        ServiceBrakeLabel.setText("Service Brake");

        ServiceBreakSlider.setValue(0);

        PowerLabel.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        PowerLabel.setText("Power");

        PropertiesHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PropertiesHeader.setText("Properties");

        CommandsHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CommandsHeader.setText("Commands ");

        EmergencyBrake.setBackground(new java.awt.Color(255, 0, 51));
        EmergencyBrake.setText("EMERGENCY BRAKE");
        EmergencyBrake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmergencyBrakeActionPerformed(evt);
            }
        });

        ACValue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ACValueStateChanged(evt);
            }
        });

        RightDoorsValue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Closed", "Open" }));

        LeftDoorsValue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Closed", "Open" }));

        InteriorLightsValue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "On", "Off" }));

        HeadlightsValue.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "On", "Off" }));

        FailureModesHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        FailureModesHeader.setText("Failure Modes");

        AnnouncementsLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        AnnouncementsLabel.setText("Announcements");

        AnnouncementsTextArea.setColumns(20);
        AnnouncementsTextArea.setRows(5);
        AnnouncementsBox.setViewportView(AnnouncementsTextArea);

        CurrentTrainHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        CurrentTrainHeader.setText("Current Train:");

        CurrentStationValue.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        CurrentStationValue.setText("DOWNTOWN");

        PowerValue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PowerValue.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PowerValue.setText("0 kW");

        EngineFailureLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        EngineFailureLabel.setText("ENGINE FAILURE: N/A");

        SignalFailureLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SignalFailureLabel.setText("SIGNAL PICKUP FAILURE: N/A");

        BrakeFailureLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BrakeFailureLabel.setText("BRAKE FAILURE: N/A");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AnnouncementsLabel)
                                .addGap(830, 830, 830))
                            .addComponent(AnnouncementsBox))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AuthorityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CurrentTrainHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TrainSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(118, 118, 118)
                                    .addComponent(PropertiesHeader))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(ACLabel)
                                            .addGap(32, 32, 32)
                                            .addComponent(ACValue, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(CurrentStationHeader, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(HeadlightsLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(LeftDoorsLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(LeftDoorsValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(RightDoorsLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(RightDoorsValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(InteriorLightsLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(InteriorLightsValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(HeadlightsValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(CurrentStationValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(KiLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(KpLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(38, 38, 38)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CurrentSpeedLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SuggestedSpeedLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(PowerLabel)
                                .addGap(364, 364, 364))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FailureModesHeader)
                                    .addComponent(EngineFailureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SignalFailureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BrakeFailureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(153, 153, 153))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(EmergencyBrake, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(229, 229, 229))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ServiceBrakeLabel)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(PowerValue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(61, 61, 61))
                                        .addComponent(CommandsHeader)))
                                .addGap(315, 315, 315))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ServiceBreakSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(289, 289, 289))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CurrentTrainHeader)
                    .addComponent(TrainSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(PropertiesHeader)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SuggestedSpeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(CommandsHeader)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PowerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CurrentSpeedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PowerValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(AuthorityLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(KiLabel)
                                .addGap(15, 15, 15)
                                .addComponent(KpLabel)
                                .addGap(18, 18, 18)
                                .addComponent(CurrentStationHeader)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CurrentStationValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(ServiceBrakeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ServiceBreakSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(EmergencyBrake, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ACLabel)
                            .addComponent(ACValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FailureModesHeader)
                        .addGap(32, 32, 32)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LeftDoorsLabel)
                            .addComponent(LeftDoorsValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(EngineFailureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RightDoorsLabel)
                            .addComponent(RightDoorsValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InteriorLightsLabel)
                            .addComponent(InteriorLightsValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HeadlightsLabel)
                            .addComponent(HeadlightsValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(SignalFailureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(BrakeFailureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(AnnouncementsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnnouncementsBox, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>                        

    private void EmergencyBrakeActionPerformed(java.awt.event.ActionEvent evt) {                                               
        trains.get(selectedTrainIndex).setEmergencyBrake(EmergencyBrake.isSelected());
        displayValues();
    }                                              

    private void TrainSelectorActionPerformed(java.awt.event.ActionEvent evt) {                                              
        selectedTrainIndex = TrainSelector.getSelectedIndex();
        displayValues();
    }                                             

    private void ACValueStateChanged(javax.swing.event.ChangeEvent evt) {                                     
        trains.get(selectedTrainIndex).setTemperature((int) ACValue.getValue());
        displayValues();
    }                                    

     private void displayValues(){
        Train t = trains.get(selectedTrainIndex);
        
        TrainSelector.setSelectedIndex(selectedTrainIndex);
        
        //checkboxes
        if(t.isBrakeFailure()) 
            BrakeFailureLabel.setText("BRAKE FAILURE:  Active");
        else BrakeFailureLabel.setText("BRAKE FAILURE:  OFF");
        if(t.isEngineFailure()) 
            EngineFailureLabel.setText("ENGINE FAILURE:  Active");
        else EngineFailureLabel.setText("ENGINE FAILURE:  OFF");
        if(t.isSignalFailure()) 
            SignalFailureLabel.setText("SIGNAL FAILURE:  Active");
        else SignalFailureLabel.setText("SIGNAL FAILURE:  OFF");
        
        ACValue.setValue(t.getTemperature());
        EmergencyBrake.setSelected(t.isEmergencyBrake());
        //activeTimeLabel.setText("Time Active: "+ t.getTime() + " seconds");
        //forceLabel.setText("Force: "+ t.getForce() + " N");
        PowerValue.setText(t.getPower() +" kw");
        SuggestedSpeedLabel.setText("Suggested Speed: "+ t.getSuggestedSpeed() +" mph");
        CurrentSpeedLabel.setText("Current Speed: "+ t.getActualSpeed() +" mph");
        //serviceBrakeLabel.setText("Service Brake: "+ getStateString(t.isServiceBrake()));
        CurrentStationValue.setText( t.getStation().toUpperCase());
        AuthorityLabel.setText( "Authority: " + t.getAuthority() + " ft.");
        //advertisementsLabel.setText("Advertisements: "+ getStateString(t.isAdvertisements()));
        //lightsLabel.setText("Lights: "+ getStateString(t.isLights()));
        //activeTimeLabel.setText("Time Active: "+ t.getTime() + " seconds");

    }
     
     private String[] getIDs(){
        
        String[] trainIDs = new String[trains.size()];
        int i=0;
        for(Train t : trains){
            trainIDs[i] = t.getTrainID();
            i++;
        }
        return trainIDs;
    }
    
    private void addTrain(Train t){
        trains.add(t);
        String[] trainIDs = getIDs();
        TrainSelector.setModel(new javax.swing.DefaultComboBoxModel<>(trainIDs));       
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify                     
    private javax.swing.JLabel ACLabel;
    private javax.swing.JSpinner ACValue;
    private javax.swing.JScrollPane AnnouncementsBox;
    private javax.swing.JLabel AnnouncementsLabel;
    private javax.swing.JTextArea AnnouncementsTextArea;
    private javax.swing.JLabel AuthorityLabel;
    private java.awt.Label BrakeFailureLabel;
    private javax.swing.JLabel CommandsHeader;
    private javax.swing.JLabel CurrentSpeedLabel;
    private javax.swing.JLabel CurrentStationHeader;
    private java.awt.Label CurrentStationValue;
    private javax.swing.JLabel CurrentTrainHeader;
    private javax.swing.JToggleButton EmergencyBrake;
    private java.awt.Label EngineFailureLabel;
    private javax.swing.JLabel FailureModesHeader;
    private javax.swing.JLabel HeadlightsLabel;
    private javax.swing.JComboBox<String> HeadlightsValue;
    private javax.swing.JLabel InteriorLightsLabel;
    private javax.swing.JComboBox<String> InteriorLightsValue;
    private javax.swing.JLabel KiLabel;
    private javax.swing.JLabel KpLabel;
    private javax.swing.JLabel LeftDoorsLabel;
    private javax.swing.JComboBox<String> LeftDoorsValue;
    private javax.swing.JLabel PowerLabel;
    private java.awt.Label PowerValue;
    private javax.swing.JLabel PropertiesHeader;
    private javax.swing.JLabel RightDoorsLabel;
    private javax.swing.JComboBox<String> RightDoorsValue;
    private javax.swing.JLabel ServiceBrakeLabel;
    private javax.swing.JSlider ServiceBreakSlider;
    private java.awt.Label SignalFailureLabel;
    private javax.swing.JLabel SuggestedSpeedLabel;
    private javax.swing.JComboBox<String> TrainSelector;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration                   

    private class Progress extends TimerTask{
        private int runs=0;
        @Override
        public void run(){            
            if(runs==0){
                addTrain(new Train("RED",1,1,40));
                addTrain(new Train("GREEN",1,1,86));
                
                System.out.println("Added Train RED1");
                System.out.println("Added Train GREEN1");
                
                trains.get(0).setSpeed(10);
                trains.get(1).setSpeed(20);
                trains.get(0).setAuthority(2000);
                trains.get(1).setAuthority(4000);
            }
            
            if(runs==30){
                addTrain(new Train("GREEN",2,1,120));
                System.out.println("Added Train GREEN2");
                trains.get(2).setSpeed(30);
                trains.get(2).setAuthority(3000);
            }
            
            if(runs==45){
                System.out.println("Changing speed for Green1...");
                trains.get(1).setSpeed(10);
            }
            
            if(runs==70){
                System.out.println("Changing speed for GREEN2");
                trains.get(2).setSpeed(40);
            }
            
            if(runs==80){
                System.out.println("Added Train RED2");
                addTrain(new Train("RED",2,1,131));
                trains.get(3).setSpeed(35);
                trains.get(3).setAuthority(2400);
            } 

            
            if(runs==105){
                System.out.println("Changing speed to 100 for RED1");
                trains.get(0).setSpeed(100);
                trains.get(0).setStation("NEXT NEXT STATION");
            }
            
            for(Train t : trains)
                t.updatePower();
            displayValues();
            //activeTimeLabel.setText("Time Active: "+ t.getTime() + " seconds");
            
            runs++;
        }
    }
}
